= Gradle Escenic Plugins
Simon Mieth <sm@ethinking.de>
v1.2, 2015-10-23 eThinking Escenic Gradle Plugin
:toc: left
:toclevels: 4
:source-highlighter: coderay
:icons: font

== Overview
The  Gradle Escenic plugins provides a complete tooling set for a smart and agile development process with the  http://www.escenic.com[Escenic Content Engine]. 


.Table of provided plugins 
[options="header"]
|=======================
|plugin Id                           |Description                                                    |DependsOn
|de.ethinking.escenic                |Manage dependencies to escenic engine and plugin repositories     |        
|de.ethinking.escenic.engine         |Provides access to engine dependencies                            |escenic 
|de.ethinking.escenic.presentation   |Provides access to presentation dependencies                      |escenic
|de.ethinking.escenic.studio         |Provides access to content studio dependencies                    |escenic
|=======================


=== Which plugin I will need for what?

The escenic content engine provides different interfaces for integration and developing custom components.  

.Table of provided plugins 
[options="header"]
|====
| Area | Plugin 
| import services, transactions handling , content integration | de.ethinking.escenic.engine
| publication, widget, frontend, presentation development      | de.ethinking.escenic.presentation
| content studio plugins                                       | de.ethinking.escenic.studio
|====

== Usage


[source, groovy]
----
plugins {
  id "de.ethinking.escenic" version "0.9.1"
  // or
  id "de.ethinking.escenic.engine" version "0.9.1"
  // or
  id "de.ethinking.escenic.presentation" version "0.9.1"
  // or
  id "de.ethinking.escenic.studio" version "0.9.1"
}
----




== Base Plugin de.ethinking.escenic 

The escenic plugin manages the complete dependencies of the escenic content engine distribution and it's plugins.

You have to use the de.ethinking.escenic plugin as parent project which will provide a local escenic repository and dependency management.


.Apply plugin
[source, groovy]
----
plugins {
  id "de.ethinking.escenic" version "0.9.1"  //<1>
}

repositories{
    escenicMaven('UserName','Password')   //<2>
    escenicLocal('my/local/repository')   //<3>
    escenicRepository('http://remote-escenic-repository>/escenic/57/','UserName','Password')//<4>
}

dependencies{
      engine 'com.escenic:engine:5.7....'   //<5>  
            
      plugin 'com.escenic:<plugin>:..'
      plugin 'com.escenic:<another plugin>:...'
      
      assembly 'com.escenic:assemblytool:...'           //<6>
}

----
<1> Apply the core plugin
<2> Setup the official escenic maven repository
<3> Setup a local filesystem based repository
<4> Setup a simple layout repository
<5> Add all your dependecies here like engine version and plugins
<6> You also need the escenic assembly tool as dependency 

=== Repository configuration

You have to provide an escenic repository where plugins and the escenic content engine distributions are available. All dependencies are resolved by gradle itself so you can use any type of repositories like maven, ivy or custom implementations. 

The escenic plugin provides shortcuts for ivy repositories with credentials and simple layout. 

[TIP]
====
By using *escenicMaven* you can choose the official escenic maven repository with your customer credentials.
====



=== Task assembly

The task *assembly* executes the esenic assembly tool and collect all content studio plugins for assembling into the content studio webstart application. 

==== Signing content studio webstart extensions

You can hook into the prepareStudioPlugins task inside your *build.gradle* to get access to all content studio plugin extensions for signing before they will be assembled in the content studio web application.

----
prepareStudioPlugins{
	doLast{
		studioPluginsLibDir.listFiles().each{ File jarFile ->
		   //sign every jar with your cert here
		}
	}	
}
----
 

=== Task init-feature 

The task *init-feature* will create a feature subproject by creating all needed folders and Gradle buildfiles. 
The subproject itself will be added to settings.gradle of the current project. 

.Table Parameters for task *init-feature*
[options="header"]
|=======================
|Parameter      |Description                                   | Optional
|feature        |The name of the feature                       | no     
|engine         |Adds escenic engine flavor                    | yes    
|presentation   |Adds escenic presentation flavor              | yes
|studio         |Adds escenic studio flavor                    | yes
|subproject     |Unkown subprojects without any escenic flavor | yes
|=======================

.Example for a *soccer* feature 
[source,sh]
----
 ./gradlew  init-feature -Dfeature=soccer -Dengine=soccer-engine -Dpresentation=soccer-widgets
----

=== Shortcuts for dependency and file resolving of plugin and content engine resources

Access to assembled war file of escenic content engine distribution

[source, groovy]
----
escenicDistributionWar(<war filename>)
----

Access to assembled war file of escenic content engine distribution as ZipTree

[source, groovy]
----
escenicDistributionWarContent(<war filename>)
----
Access to contrib files inside the escenic content engine distribution

[source, groovy]
----
escenicDistribution(<directory or file >) //<1>
----
<1> relative pathes inside content engine distribution


Collection of all assembled content engine core layer libraries

[source, groovy]
----
escenicEngineLibs()
----

You can use this shortcuts for preparing deployments with other plugins like cargo/ distribution or de.ethinking.gaffer and many other.



== Plugin de.ethinking.escenic.engine

The de.ethinking.escenic.engine plugin provides access to all libraries from the escenic distribution and all used plugins of your installation. 


.Apply plugin
[source, groovy]
----
plugins {
  id "de.ethinking.escenic.engine" version "0.x.x"  //<1>
}

//or if parent project uses de.ethinking.escenic plugin 

apply plugin:"de.ethinking.escenic.engine"

dependencies{
    compile engineAPI() //<1>
    compile engineCore()   //<2>
    compile enginePlugin('any-plugin')   //<3>
}

----
<1> Adds only the minimal need libraries of the API escenic engine layer
<2> Adds all dependencies of the API escenic engine layer
<3> Adds all dependencies of the API layer from the given plugin   



== Plugin de.ethinking.escenic.presentation

.Apply plugin
[source, groovy]
----
plugins {
  id "de.ethinking.escenic.presentation" version "0.x.x"  //<1>
}
//or

apply plugin:"de.ethinking.escenic.presentation"


dependencies{
       compile  presentationCore()                 //<2>
       compile  presentationPlugin('menu')         //<3>
}

----
<1> apply the plugin for escenic presentation support
<2> add presentation core compile dependencies
<3> add the presentation libraries of the menu plugin as compile dependencies

=== Publication Extension DSL

The publication extension provides configuration options for the resources upload task

[source, groovy]
----
publication{

 publications "publication-1","publication-2"   //<1>
 resourcesHost "dev","http://development-host:8080/escenic-admin/publication-resources/" //<2>
 resourcesHost "production","http://production-host:8080/..","admin","secret" //<3>
 resourcesHost 'stage',{   //<4>
                    url 'http://stage-backend:8080/escenic-admin/publication-resources/'
                    resourceBase project.file("build/stage")
                    user "admin"
                    password "stage"       
		}
 ignoreResourcesFailure = true    //<5>
}
----
<1> publication list for the ResourcesUpload Tasks
<2> simple resources host definition
<3> simple resources host definition with authentication
<4> advanced resources host definition (see properties below)
<5> allows to irgnore failures on resources uploads 


==== Resources host advanced properties
[options="header"]
|=======================
|Property      |Description                                   | Type
|url           | The escenic upload url                       | String
|resourceBase  | Where all resources are located              | File
|user          | User name for a protected escenic admin      | String
|password      | Password for a protected escenic admin       | String
|usePublicationDirectories | Subdirectory names are publications names instead of the _publications_ property | Boolean
|=======================


=== Resources Upload Tasks

The resources upload Tasks will be created from the configured publication extensions. For every host and publication a task will be created. Basic auth of escenic admin is supported.

----
resources-<publicationname>-<host key like dev or production>
----

or if you use *_usePublicationDirectories=true_*

----
resources-<host key like dev or production>
----

You can also use a collection task for every host to apply all necessary publication resources for a single host.

----
resourcesHost-<host key like dev or production>
----



==== Prepare resources before upload
The task *_preparePublicationResources_* allows you to process resources before they will be uploaded. All ResourcesUploadTasks depends on the  *_preparePublicationResources_* task.

.build.gralde 
[source, groovy]
----

task createResources{
 // create  or
 // validate resources here
}

preparePublicationResources.dependsOn  createResources

----


=== Merge multiple `content-type.xml` files

Instead of a single huge monolithic `content-type.xml`, you can split it into one base and multiple fragments.
To use this feature, define a task of type `MergeContentTypeTask` and set inside the required parameters. This task type will inject
fragments to a base file and create a single big `content-type.xml`.

Content types can have a preprocessing attribute `ui-groups` from `http://ethinking.de/content-type-processing` namespace, which is used to insert a reference of content type into groups.
The attribute value is a comma-separated list of group names, in which the reference will be placed.

Other preprocessing attributes are `in-publications` and `not-in-publications`. You can use these on any element
to control in which publication they will be included or excluded. Their values are comma-separated lists of publication names.

The required properties of the `MergeContentTypeTask` are:

* `String publication` - which publication to use for publication inclusion/exclusion preprocessing,
* `File baseFile` - the file into which the fragments will be injected,
* `FileCollection fragments` - files to be injected into the base (note that you can use `fileTree`) and
* `File outputFile` - where the merged file will be.

For example we have this `baseFile`:

[source, xml]
----
<?xml version="1.0" encoding="utf-8"?>
<content-types xmlns="http://xmlns.escenic.com/2008/content-type" version="4">
</content-types>
----

and a fragment XML containing group definition:

[source, xml]
----
<?xml version="1.0" encoding="utf-8"?>
<content-types xmlns="http://xmlns.escenic.com/2008/content-type"
xmlns:ui="http://xmlns.escenic.com/2008/interface-hints" version="4">
    <ui:group name="widgets_hackeshermarkt">
        <ui:label>Hackeshermarkt UI group</ui:label>
    </ui:group>
</content-types>
----

and another fragment XML containing content type definition:

[source, xml]
----
<?xml version="1.0" encoding="utf-8"?>
<content-types xmlns="http://xmlns.escenic.com/2008/content-type"
xmlns:ui="http://xmlns.escenic.com/2008/interface-hints"
xmlns:ctp="http://ethinking.de/content-type-processing" version="4"> //<1>
    <content-type name="widget_alice" ctp:ui-groups="widgets_hackeshermarkt"> //<2>
        <ui:label ctp:in-publications="one">Widget: Alice</ui:label> //<3>
    </content-type>
</content-types>
----
<1> `ctp` namespace
<2> preprocessing attribute `ui-groups`
<3> preprocessing attribute `in-publications`

The merged result for publication `one` is this:

[source, xml]
----
<?xml version="1.0"?>
<content-types xmlns="http://xmlns.escenic.com/2008/content-type" version="4">
    <ui:group xmlns:ui="http://xmlns.escenic.com/2008/interface-hints" name="widgets_hackeshermarkt">
        <ui:label>Hackeshermarkt UI group</ui:label>
        <ui:ref-content-type name="widget_alice"/>
    </ui:group>
    <content-type name="widget_alice">
        <ui:label xmlns:ui="http://xmlns.escenic.com/2008/interface-hints">Widget: Alice</ui:label>
    </content-type>
</content-types>
----

Define the task of type `MergeContentTypeTask` with your own configuration e.g. like this:

[source, groovy]
----
task mergeContentType(type: de.ethinking.gradle.task.escenic.MergeContentTypeTask) {
    publication = 'news'
    baseFile = file('config/content-type.xml')
    fragments = fileTree('config/fragments') {
        include '*/content-type.xml'
    }
    outputFile = new File(buildDir, 'content-type.xml')
}
----







== Plugin de.ethinking.escenic.studio

.Apply plugin
[source, groovy]
----
plugins {
  id "de.ethinking.escenic.studio" version "0.x.x"  //<1>
}

//or if parent project uses de.ethinking.escenic plugin 

apply plugin:"de.ethinking.escenic.studio"

dependencies{
    compile  studioCore()                     //<2>
    compile  studioPlugin('analytics')        //<3>
}
----
<1> apply the studio plugin
<2> add content studio libs as compile dependency
<3> add content studio libs of an plugin as compile dependency


== Example project 

=== Setup the parent project 

.The parent build.gradle file
[source, groovy]
----

plugins {
  id "de.ethinking.escenic" version "0.x.y"  //<1>
}

repositories{
    escenicRepository('http://<Escenic distribution repository>/escenic/57/','***','***')
}

subprojects {        //<1>

    apply plugin: 'java'
    apply plugin: 'eclipse'


    [compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

    repositories {
        mavenCentral()
    }

}

dependencies{
      engine 'com.escenic:engine:6.7.xxxx'
      plugin 'com.escenic:widget-framework-core:4.5.xxxx'
      plugin 'com.escenic:analysis-engine:2.7.0.148640'
      .....
      assembly 'com.escenic:assemblytool:2.0.7'
}

task wrapper(type: Wrapper) {       //<2>
    gradleVersion = '4.6'
}

----
<1> Configure all subproject as java projects and add support for eclipse
<2> Use the gradle wrapper to simplify gradle installation


== Copyright and License

Copyright 2014-2015 (c) http://ethinking.de[eThinking GmbH]  and contributors.

All versions, present and past, of Gradle Escenic Plugin are licensed under Apache 2.0 license.
